feat : user 도메인 crud 테스트
f-lab-edu/fream pull request #30
Opened 2021-11-21 10:21 UTC by HyundeokPark

user,address 쪽 기본적인 crud 생성과 테스트 입니다.

2021-11-21 12:53 UTC, cocahack requested changes
mapper 테스트들 상속 클래스 변경 부탁드립니다~

2021-11-21 12:53 UTC, cocahack commented on src/test/groovy/kr/flab/fream/mybatis/mapper/user/AddressMapperSpec.groovy
> +class AddressMapperSpec extends Specification {
여기도 마찬가지로 수정 부탁드립니다

2021-11-21 12:53 UTC, cocahack commented on src/test/groovy/kr/flab/fream/mybatis/mapper/product/SizeMapperSpec.groovy
> +class SizeMapperSpec extends Specification {
mapper 테스트들은 `DatabaseTest` 상속해주세요. 그냥 `Specification` 만 쓰면 CI에서 테스트 제대로 안될거에요.

2021-11-21 12:53 UTC, cocahack commented on src/test/groovy/kr/flab/fream/mybatis/mapper/user/UserMapperSpec.groovy
> +class UserMapperSpec extends Specification {
여기도 바꿔주세요

2021-11-22 10:35 UTC, f-lab-joseph requested changes

2021-11-22 10:35 UTC, f-lab-joseph commented on src/main/java/kr/flab/fream/domain/user/model/Address.java
> +    Long id;
필드에 접근 제한자가 없습니다. 다른 코드 스타일과 맞춰주세요.

2021-11-22 10:35 UTC, f-lab-joseph commented on src/main/java/kr/flab/fream/domain/user/model/Address.java
> +    long userId;
위는 래퍼, 아래는 프리미티브 타입입니다. 
프리미티브타입은 기본값을 갖기 떄문에, 의도와 조금 다르게 동작할 가능성이 높습니다. (DB 필드 타입에 따라)
래퍼타입으로 구성해주세요.

2021-11-22 21:45 UTC, HyundeokPark commented on src/test/groovy/kr/flab/fream/mybatis/mapper/user/AddressMapperSpec.groovy
> +class AddressMapperSpec extends Specification {
넵 수정 하겠습니다!

2021-11-22 21:45 UTC, HyundeokPark commented on src/main/java/kr/flab/fream/domain/user/model/Address.java
> +    Long id;
넵 추가하겠습니다!

2021-11-22 21:45 UTC, HyundeokPark commented on src/main/java/kr/flab/fream/domain/user/model/Address.java
> +    long userId;
넵 감사합니다!!

2021-11-23 04:21 UTC, cocahack commented
CI 로그가 너무 많이 찍혀서 어디서 fail 생겼는지 못찾겠네요. CI 스크립트하고 debug 레벨 수정 해야겠습니다.

---

@HyundeokPark 

로컬에서 테스트 실행하실 때는 문제가 없으셨나요?

2021-11-23 04:28 UTC, cocahack approved these changes

2021-11-23 13:21 UTC, HyundeokPark commented
@cocahack 일단 두번째 커밋은 run githook을 했을때 통과되서 커밋한건데, gradlew clean check -i 실행하니 뭔가 막 뜨더라구요.. 일단 오늘 로그좀 계속 보려고 합니다!

2021-11-24 03:45 UTC, f-lab-joseph approved these changes
DB 테스트도 좋지만 다음에는 unitTest 위주로 작성해주시면 좋을 것 같습니다.

2021-11-26 08:32 UTC, f-lab-joseph commented on src/main/resources/db/migration/V1.3.0__User.sql
> +    UNIQUE KEY (email)
지금 보니 가입일, 수정일 등의 날짜 정보가 없네요.

2021-11-26 08:33 UTC, f-lab-joseph commented on src/main/resources/db/migration/V1.3.0__User.sql
> +    FOREIGN KEY (user_id) REFERENCES users(id)
생성일등의 날짜 데이터는 필요없을까요 ?

2021-11-26 08:35 UTC, f-lab-joseph reviewed
db column 관련 달아드린 내용은 별도의 이슈로 뺴셔서 처리해주시고 추가 변경사항 없으면 머지해주세요.

2021-11-28 07:24 UTC, merged