37 user login
f-lab-edu/fream pull request #44
Opened 2021-12-25 08:23 UTC by HyundeokPark

**구현한 내용**

1. 사용자 email, password을 입력값으로 로그인
2. loginInterceptor로 현재 user/login을 제외한 나머지 user/** api는 로그인 상태를 확인
3. logout 기능으로 session에 userInfo 값이 있으면 session.invalidate() 실행
4. 세션 클러스터링으로 spring-session-jdbc사용, mySql에 session 관련 테이블 생성 
#37

2021-12-25 09:08 UTC, cocahack requested changes

2021-12-25 09:08 UTC, cocahack commented on src/main/java/kr/flab/fream/controller/user/UserController.java
> +        UserDto userInfo = userService.userLogin(userDto);
로그인의 입력과 출력이 모두 같은 DTO를 쓰고 있네요. 로그인 요청을 위한 DTO를 따로 분리하면 좋을 것 같습니다.

2021-12-25 09:08 UTC, cocahack commented on src/main/java/kr/flab/fream/controller/user/UserController.java
> +        }
유저 정보가 존재하지 않을 때 서비스 레이어에서 unchecked exception 을 던지게 만들면 이 부분에 if 문을 제거할 수 있습니다. 

그리고 로그인 실패 시 발생한 예외를 HTTP 401 상태로 반환할 수 있게 만들어 주시면 좋겠습니다. 이 예외는 로그인 url에서만 발생하니 전역적으로 예외를 처리하는 `GlobalExceptionHandler` 와는 다른 방식으로 구현하는게 좋겠습니다. 

급하게 찾은 자료도 같이 첨부할게요.

- https://bcp0109.tistory.com/303
- https://cheese10yun.github.io/spring-guide-exception

2021-12-25 09:08 UTC, cocahack commented on src/main/java/kr/flab/fream/interceptor/LoginInterceptor.java
> +        }
로그인이 필요한 기능을 사용할 때 만약 로그인이 되어있지 않다면 403 을 던져야 합니다. 

인터셉터에서 예외를 던지면 그러한 처리가 현재 가능한가요? 

그리고 이와 관련한 테스트 케이스(로그인 없이 기능을 사용하면 403 status code을 리턴하는 테스트)가 없다면 이 부분도 테스트해 주시면 좋을 듯 합니다.

2021-12-25 09:09 UTC, cocahack commented
추가로 `TemporaryAuthenticationResolver` 제거하고 세션에서 유저 정보를 가져올 수 있도록 `AbstractAuthenticationResolver` 의 구현체도 작성 부탁드립니다!

2021-12-25 12:48 UTC, cocahack commented on src/main/java/kr/flab/fream/controller/user/UserController.java
> +            @NotNull  @RequestBody UserDto loginInfo) throws Exception {
@Valid 를 붙여주셔야 입력 값 검증 기능을 쓸 수 있어요

2021-12-28 16:01 UTC, HyundeokPark commented on src/main/java/kr/flab/fream/interceptor/LoginInterceptor.java
> +        }
인터셉터에서 이미 구현해두신 GlobalExceptionHandler를 잘타는걸 확인했습니다.

말씀해주신 httpStatus 코드는 401이랑 403이 햇갈려서 검색을 해봤는데요.
개인적으로는 403보다는 401이 더 나을것 같은 생각이 들어서 코멘트 남깁니다!
- 401(UnAuthorized) : 인증이 되지 않은 요청,
- 403(Forbidden) : 인증이 된 요청이지만 해당api에 대한 권한이 없음 인가X 

참고한 사이트 링크 해드립니다.

[https://sas-study.tistory.com/326](url)
[https://mangkyu.tistory.com/146](url)
[https://youtu.be/JZgD8aPkHSc](url)

2021-12-29 03:58 UTC, cocahack commented on src/main/java/kr/flab/fream/interceptor/LoginInterceptor.java
> +        }
말씀하신게 맞습니다. 401로 처리 부탁드립니다. 

403은 다른 유저가 생성한 입찰을 제어하는 상황처럼 권한이 없는 경우에 던지는게 맞습니다. 제가 헷갈리게 잘못 말씀드렸네요

2022-01-01 08:23 UTC, cocahack requested changes

2022-01-01 08:23 UTC, cocahack commented on src/main/java/kr/flab/fream/config/WebConfig.java
> +                .excludePathPatterns("/user/login/**");
입찰 등록, 거래 등은 인터셉터를 타야하지만, 단순 조회는 인증없이도 가능해야 합니다. 이런 기능도 가능할까요?

2022-01-01 08:23 UTC, cocahack commented on src/main/java/kr/flab/fream/controller/user/UserDto.java
>      String password;
응답 body 객체라면 password는 제거해주세요.

2022-01-01 08:23 UTC, cocahack commented on src/main/java/kr/flab/fream/auth/AuthenticationResolver.java
>                  LocalDateTime.now(), null);
주석 제거 부탁드립니다~

2022-01-10 15:04 UTC, HyundeokPark commented
메인브랜치와 머지되면 바로 회원가입 기능도 따라서 올리겠습니다!~~

2022-01-11 11:09 UTC, cocahack commented on src/main/java/kr/flab/fream/config/WebConfig.java
> +                .excludePathPatterns("/user/login/**");
이 부분은 혹시 찾아보셨을까요?

2022-01-11 12:49 UTC, HyundeokPark commented on src/main/java/kr/flab/fream/config/WebConfig.java
> +                .excludePathPatterns("/user/login/**");
config쪽에서 설정은 불가능하고 preHandle() 메소드 내에서 if/else로만 가능할것 같습니다. http메소드를 받을수 있는건 따로 없더라구요! ㅠㅠ

2022-01-11 13:17 UTC, cocahack approved these changes

2022-01-11 13:24 UTC, f-lab-joseph approved these changes

2022-01-11 13:26 UTC, merged