bug : 주소값 없을 시 회원정보 조회 실패 수정
f-lab-edu/fream pull request #56
Opened 2022-02-06 06:18 UTC by HyundeokPark

#54 
해당 이슈의 오류 조치입니다.

# 예상한 오류지점들
1. 401에러는 인터셉터에서 처리해주기 때문에, 인터셉터 설정이 잘못되었다.
2. DB에 회원정보가 들어가지 않았다.
3. 비지니스 로직에 문제가 있다.

# 확인결과
1. 인터셉터 설정은 잘 되어있다. 로그인과 회원가입 경로에 대해서 제외되어있었다.
2. DB에도 회원정보는 들어가 있었다.
3. 비지니스 로직인 쿼리문에서 문제가 발견되었다.
` FROM  user AS u
                    JOIN address AS a ON u.id = a.user_id
        WHERE u.email = #{email}`
 outer join이 아니라 inner join을 사용하게 되면서 DB에서 회원정보를 찾지 못했기 때문이다.
 
 # 개선 및 변경할 점
1. 회원가입시 주소를 받지 않도록 되어 있어 회원가입 API 스팩 수정 필요
2. @NotNull 어노테이션의 검증시 제대로된 예외처리를 하지 않는 경우 발견, 수정필요

2022-02-06 06:22 UTC, HyundeokPark commented
@cocahack 
어제 말씀해주신 이메일,비밀번호가 올바름에도 나오는 401 error는 비지니스 로직에 결함이 있어서 회원을 찾지 못함에 따라 나온 정상적인 예외 처리 같습니다. 혹시 저번에 말씀해주셨던 스프링과 관련된 예외처리 오류?... 가 NotNull 어노테이션의 검증시 제대로된 예외처리를 하지 않는 경우 발견, 수정필요 요 부분과 동일한걸까요??

2022-02-06 06:24 UTC, cocahack commented
이번 이슈와 관련된 테스트 케이스도 추가 부탁드릴게요. 서비스 레이어와 DAO 레이어를 함께 검증하는 integration test 방식으로 Address가 없는 유저가 로그인할 때 인증 정보가 맞다면 그 경우와 관련된 리턴 값을 서비스가 잘 반환하는지 보면 될 것 같네요.

2022-02-06 06:28 UTC, cocahack commented
> @cocahack 어제 말씀해주신 이메일,비밀번호가 올바름에도 나오는 401 error는 비지니스 로직에 결함이 있어서 회원을 찾지 못함에 따라 나온 정상적인 예외 처리 같습니다. 혹시 저번에 말씀해주셨던 스프링과 관련된 예외처리 오류?... 가 NotNull 어노테이션의 검증시 제대로된 예외처리를 하지 않는 경우 발견, 수정필요 요 부분과 동일한걸까요??

500 에러 발생해서 에러 페이지로 리다이렉트 될 때 인터셉터에서 잘못 처리하는 이슈였던 것 같은데, 확실치 않네요. 시나리오 테스트 해보시면서 찾아봐주세요. 억지로 에러가 발생할만한 요청을 계속 날리다 발견했던 것 같아요. 이번 이슈와는 관련없는 것 같네요.

2022-02-06 06:29 UTC, cocahack requested changes

2022-02-06 06:29 UTC, cocahack commented on src/main/resources/kr/flab/fream/mybatis/mapper/user/UserMapper.xml
> +            LEFT OUTER JOIN address AS a ON u.id = a.user_id
이번 이슈와 관련된 테스트 케이스도 추가 부탁드릴게요. 서비스 레이어와 DAO 레이어를 함께 검증하는 integration test 방식으로 Address가 없는 유저가 로그인할 때 인증 정보가 맞다면 그 경우와 관련된 리턴 값을 서비스가 잘 반환하는지 보면 될 것 같네요.

2022-02-06 06:29 UTC, HyundeokPark commented on src/main/resources/kr/flab/fream/mybatis/mapper/user/UserMapper.xml
> +            LEFT OUTER JOIN address AS a ON u.id = a.user_id
넵!~ 추가하겠습니다~~

2022-02-06 12:04 UTC, f-lab-joseph commented
NotNull 어노테이션의 검증시 제대로된 예외처리를 하지 않는 경우  가 어떤 경우인가요 ?

2022-02-08 14:30 UTC, HyundeokPark commented
> NotNull 어노테이션의 검증시 제대로된 예외처리를 하지 않는 경우 가 어떤 경우인가요 ?

404에러와 함께 에러메세지가 나오는데, 프로젝트에서 설정한 GlobalExceptionHandler를 타지 않는 문제입니다.

2022-02-10 15:22 UTC, HyundeokPark commented on src/main/resources/kr/flab/fream/mybatis/mapper/user/UserMapper.xml
> +            LEFT OUTER JOIN address AS a ON u.id = a.user_id
테스트 코드  통합테스트로 추가했습니다~

2022-02-10 15:41 UTC, cocahack approved these changes

2022-02-13 09:32 UTC, merged